server:
  port: 9527
  max-http-header-size: 65536
  tomcat:
    max-http-post-size: 41943046




spring:

    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        # 初始化大小，最小，最大
        initialSize: 1
        # 配置获取连接等待超时的时间(毫秒)
        maxWait: 60000
        minIdle: 1
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20

    freemarker:
      suffix: .ftl  #后缀名
      content-type: text/html
      enabled: true
      cache: false #缓存配置
      template-loader-path: classpath:/templates/ #模板加载路径 按需配置
      charset: UTF-8 #编码格式
      settings:
        number_format: '0.##'
      allow-request-override: true
      check-template-location: true
      expose-request-attributes: true
      expose-session-attributes: true
      expose-spring-macro-helpers: true
      request-context-attribute: req

      redis:
        database: 0
        host: localhost
        port: 6379
        # 连接超时时间 单位 ms（毫秒）
        timeout: 3000
        pool:
            max-idle: 8  # 连接池中的最大空闲连接，默认值也是8。
            min-idle: 0  #连接池中的最小空闲连接，默认值也是0。
            max-active: 8  # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
            max-wait: -1  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.edu.demo.pojo.entity

  mapper:
    mappers:  com.edu.demo.mapper
    not-empty: false
    identity: MYSQL

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


